language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: deps=no
    - php: 7.1
      env: deps=high
    - php: 7.2
      env: deps=no
    - php: 7.2
      env: deps=high
    - php: 7.3
      env: deps=no
    - php: 7.3
      env: deps=high
    - php: 7.4
      env: deps=no
    - php: 7.4
      env: deps=high
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
before_install:
    - ./tests/script/travis_before_install.sh
install:
    - ./tests/script/travis_install.sh
script:
    - ./tests/script/travis_script.sh
after_success:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l PHP -r tests/_output/coverage.xml
